//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationTH.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class KHACHHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACHHANG()
        {
            this.DONDATHANGs = new HashSet<DONDATHANG>();
        }
    
        public int MaKH { get; set; }

        [Required(ErrorMessage = "Họ tên khách hàng is required.")]
        [StringLength(50, ErrorMessage = "Họ tên khách hàng cannot be longer than 50 characters.")]
        public string HoTen { get; set; }

        [Required(ErrorMessage = "Tên đăng nhập is required.")]
        [StringLength(50, ErrorMessage = "Tên đăng nhập cannot be longer than 50 characters.")]
        public string Taikhoan { get; set; }

        [Required(ErrorMessage = "Mật khẩu is required.")]
        [StringLength(100, MinimumLength = 6, ErrorMessage = "Mật khẩu must be at least 6 characters.")]
        public string Matkhau { get; set; }

        [Required(ErrorMessage = "Email is required.")]
        [EmailAddress(ErrorMessage = "Invalid email format.")]
        [StringLength(100, ErrorMessage = "Email cannot be longer than 100 characters.")]
        public string Email { get; set; }

        [StringLength(200, ErrorMessage = "Địa chỉ không thể dài hơn 200 ký tự.")]
        public string DiachiKH { get; set; }

        [Phone(ErrorMessage = "Invalid phone number.")]
        [StringLength(50, ErrorMessage = "Số điện thoại không thể dài hơn 50 ký tự.")]
        public string DienthoaiKH { get; set; }

        [DataType(DataType.Date, ErrorMessage = "Invalid date format.")]
        public Nullable<System.DateTime> Ngaysinh { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONDATHANG> DONDATHANGs { get; set; }
    }
}
